// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JorgeSaicoski/ledger-service/internal/validator (interfaces: Validator)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_validator.go -package=mocks github.com/JorgeSaicoski/ledger-service/internal/validator Validator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/JorgeSaicoski/ledger-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateTransactionRequest mocks base method.
func (m *MockValidator) ValidateTransactionRequest(req models.TransactionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTransactionRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTransactionRequest indicates an expected call of ValidateTransactionRequest.
func (mr *MockValidatorMockRecorder) ValidateTransactionRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTransactionRequest", reflect.TypeOf((*MockValidator)(nil).ValidateTransactionRequest), req)
}

// ValidateUUID mocks base method.
func (m *MockValidator) ValidateUUID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUUID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUUID indicates an expected call of ValidateUUID.
func (mr *MockValidatorMockRecorder) ValidateUUID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUUID", reflect.TypeOf((*MockValidator)(nil).ValidateUUID), id)
}
